var edificios = {
    
    
    Camino1: {
        titulo: {
            es: "Camino",
            en: "Road",
        },
        tipo: "Camino1",
        imagen: 'imagenes/huerta/edificios/Camino.png',
        ancho: 200,
        alto: 96,
        xCuadro: 0,
        xCuadroTermino: 200,
        yCuadro: 0,
        yCuadroTermino: 96,
        construccion: {
            costo: -3,
            demoler: -2,
        },
    },
    Fuente1: {
        titulo: {
            es: "Fuente Pequeña",
            en: "Small Fountain",
        },
        tipo: "Fuente1",
        imagen: 'imagenes/huerta/edificios/Fuente.png',
        ancho: 200,
        alto: 123,
        xCuadro: 0,
        xCuadroTermino: 200,
        yCuadro: 26.6,
        yCuadroTermino: 123,
        construccion: {
            costo: -30,
            demoler: -15,
        },
    },
    Estanque1: {
        titulo: {
            es: "Estanque Mediano",
            en: "Medium Pond",
        },
        tipo: "Estanque1",
        imagen: 'imagenes/huerta/edificios/Estanque.png',
        ancho: 400,
        alto: 259,
        xCuadro: 0,
        xCuadroTermino: 400,
        yCuadro: 67.29,
        yCuadroTermino: 259,
        cantidadCuadrosX: 2,
        cantidadCuadrosY: 2,
        construccion: {
            costo: -300,
            demoler: -150,
        },
    },
    Monumento1: {
        titulo: {
            es: "Monumento",
            en: "Monument",
        },
        tipo: "Monumento1",
        imagen: 'imagenes/huerta/edificios/Monumento.png',
        ancho: 200,
        alto: 211,
        xCuadro: 0,
        xCuadroTermino: 200,
        yCuadro: 114.78,
        yCuadroTermino: 211,
        construccion: {
            costo: -400,
            demoler: -200,
        },
    },
    Casa1: {
        titulo: {
            es: "Casa Sencilla",
            en: "Simple House",
        },
        tipo: "Casa1",
        imagen: 'imagenes/huerta/edificios/Casa-1.png',
        ancho: 400,
        alto: 280,
        xCuadro: 0,
        xCuadroTermino: 400,
        yCuadro: 87.75,
        yCuadroTermino: 280,
        cantidadCuadrosX: 2,
        cantidadCuadrosY: 2,
        construccion: {
            costo: -500,
            demoler: -250,
        },
    },
    
    Granero1: {
        titulo: {
            es: "Granero",
            en: "Barn",
        },
        tipo: "Granero1",
        imagen: 'imagenes/huerta/edificios/Granero1.png',
        ancho: 400,
        alto: 232,
        xCuadro: 0,
        xCuadroTermino: 400,
        yCuadro: 39.856,
        yCuadroTermino: 232,
        cantidadCuadrosX: 3,
        cantidadCuadrosY: 3,
        construccion: {
            costo: -1000,
            demoler: -500,
        },
    },
    Estanque2: {
        titulo: {
            es: "Estanque",
            en: "Pond",
        },
        tipo: "Estanque2",
        imagen: 'imagenes/huerta/edificios/Estanque2.png',
        ancho: 400,
        alto: 274,
        xCuadro: 0,
        xCuadroTermino: 400,
        yCuadro: 82.33,
        yCuadroTermino: 274,
        cantidadCuadrosX: 3,
        cantidadCuadrosY: 3,
        construccion: {
            costo: -1200,
            demoler: -600,
        },
    }, 
    Granero2: {
        titulo: {
            es: "Granero Mejorado",
            en: "Improved Barn",
        },
        tipo: "Granero2",
        imagen: 'imagenes/huerta/edificios/Granero2.png',
        ancho: 400,
        alto: 258,
        xCuadro: 0,
        xCuadroTermino: 400,
        yCuadro: 66.117,
        yCuadroTermino: 258,
        cantidadCuadrosX: 3,
        cantidadCuadrosY: 3,
        construccion: {
            costo: -1800,
            demoler: -900,
        },
    },
    Vivero: {
        titulo: {
            es: "Vivero",
            en: "Plant Nursery",
        },
        tipo: "Vivero",
        imagen: 'imagenes/huerta/edificios/Vivero.png',
        ancho: 400,
        alto: 288,
        xCuadro: 0,
        xCuadroTermino: 400,
        yCuadro: 95.938,
        yCuadroTermino: 288,
        cantidadCuadrosX: 3,
        cantidadCuadrosY: 3,
        construccion: {
            costo: -5000,
            demoler: -2500,
        },
    },
    Casa2: {
        titulo: {
            es: "Casa Grande",
            en: "Big House",
        },
        tipo: "Casa2",
        imagen: 'imagenes/huerta/edificios/Casa-2.png',
        ancho: 600,
        alto: 302,
        xCuadro: 0,
        xCuadroTermino: 600,
        yCuadro: 14.244,
        yCuadroTermino: 302,
        cantidadCuadrosX: 4,
        cantidadCuadrosY: 4,
        construccion: {
            costo: -9000,
            demoler: -4500,
        },
    },
    
};
